#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
killall volumeicon

xrandr --output eDP-1 --primary --auto --output HDMI-1 --auto --above eDP-1
# xrandr --output HDMI-1 --auto --above eDP-1 --primary
picom --backend glx --vsync -b &
nitrogen --restore &
nm-applet &
volumeicon &
blueman-applet &
$HOME/.config/polybar/launch.sh

xset s 300 5
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock


bspc monitor eDP-1 -d 1 2 3 4

bspc monitor HDMI-1 -d  5 6 7 8

bspc config border_width         2
bspc config window_gap           8

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
